version: "3"

services:
  db:
    image: redis:5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - "6379:6379"    
    networks:
      - redis-net
    volumes:
      - redis-data:/data
    restart: always

networks:
  redis-net:

volumes:
  redis-data: